#!/bin/bash

#****************************************************************************************************#
#                                        TESTCHAIN-BP-MONITOR                                        #
#****************************************************************************************************#

#----------------------------------------------------------------------------------------------------#
# IF THE USER HAS NO ROOT PERMISSIONS THE SCRIPT WILL EXIT                                           #
#----------------------------------------------------------------------------------------------------#

if (($EUID!=0))
then
  echo "You must be root to run this script" 2>&1
  exit 1
fi

#----------------------------------------------------------------------------------------------------#
# CONFIGURATION VARIABLES                                                                            #
#----------------------------------------------------------------------------------------------------#

second_date=$(date -d $now +%s)
minute_date=$(date -d $now +%s%N)
current_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
max_queued_msg_lines="50"
log_file="/root/remnode.log"
state_file="/root/check-bp-monitor"
create_dir="/root/remblock/bp-monitor"
config_file="/root/remblock/bp-monitor/config"
temp_dir="/root/remblock/bp-monitor/bp-monitor-temp"
cron_cmd="/root/remblock/bp-monitor/testchain-bp-monitor"
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"

#----------------------------------------------------------------------------------------------------#
# CREATE DIRECTORY IF IT DOESN'T EXIST                                                               #
#----------------------------------------------------------------------------------------------------#

if [ ! -d "$create_dir" ]
then
  mkdir -p "$create_dir"
  cp -p "$0" "$create_dir"
fi

#----------------------------------------------------------------------------------------------------#
# CREATE STATE FILE IF IT DOESN'T EXIST                                                              #
#----------------------------------------------------------------------------------------------------#

if [ ! -f "$state_file" ]
then
cat > "$state_file" << 'DOC'
on
DOC
fi

#-----------------------------------------------------------------------------------------------------
# SCHEDULE CRON FOR THE BP MONITOR SCRIPT
#-----------------------------------------------------------------------------------------------------

if ! crontab -l | grep -q "testchain-bp-monitor"
then
  (crontab -l ; echo "* * * * * $create_dir/testchain-bp-monitor >> $create_dir/${SCRIPT_LOG_FILE} 2>&1") | crontab -
fi

#****************************************************************************************************#
#                                            FUNCTIONS                                               #
#****************************************************************************************************#

#----------------------------------------------------------------------------------------------------#
# FUNCTION TO TRANSLATE THE TIME FORMAT FROM REMCLI FORMATE TO EPOCH TIME                            #
#----------------------------------------------------------------------------------------------------#

function remnodelogtime_to_date() {
  temp_date="$( echo $1 | awk -F '.' '{ print $1}' | tr '-' '/' | tr 'T' ' ')"
  echo $(date "+%s" -d "$temp_date")
}

#----------------------------------------------------------------------------------------------------#
# FUNCTION TO GET YES OR NO ANSWER FROM USER                                                         #
#----------------------------------------------------------------------------------------------------#

function get_user_answer_yn(){
  while :
  do
    read -p "$1 [y/n]: " answer
    answer="$(echo $answer | tr '[:upper:]' '[:lower:]')"
    case "$answer" in
      yes|y) return 0 ;;
      no|n) return 1 ;;
      *) echo  "Invalid Answer [yes/y/no/n expected]";continue;;
    esac
  done
}

#----------------------------------------------------------------------------------------------------#
# FUNCTION TO GET VALUE FROM THE CONFIG FILE AND RETURN IT WITH THE VARIABLE "global_value"          #
#----------------------------------------------------------------------------------------------------#

function get_config_value() {
  global_value=$(grep -v '^#' "$config_file" | grep "^$1=" | awk -F '=' '{print $2}')
  if [ -z "$global_value" ]
  then
    return 1
  else
    return 0
  fi
}

#----------------------------------------------------------------------------------------------------#
# FUNCTION TO CHECK REMCLI GET INFO RESPONSE                                                         #
#----------------------------------------------------------------------------------------------------#

function check_remcli_info(){
  if ! timeout 10s remcli get info 2>&1 | grep server_version &>/dev/null
  then
    curl -s -X POST https://api.telegram.org/bot$telegram_token/sendMessage -d chat_id=$telegram_chatid -d text="$servername failed to receive a response from \"remcli get info\"" &>/dev/null
  fi
}

#----------------------------------------------------------------------------------------------------#
# FUNCTION TO CHECK WHETHER PRODUCER IS PRODUCING BLOCKS                                             #
#----------------------------------------------------------------------------------------------------#

function check_produce_minutes(){
  last_block_date=$(remcli -u https://testchain.remme.io get table rem rem producers -L $accountname -U $accountname | grep 'last_block_time' | awk '{print $2}' | tr -d '"' | tr -d ',')
  last_block=$(remnodelogtime_to_date "$last_block_date")
  current_minutes=$(( ($second_date - $last_block) / 60 ))
  config_minutes_in_seconds=$(( (check_last_block_minutes * 60) ))
  if (( ($second_date - $last_block) >= $config_minutes_in_seconds ))
  then
    curl -s -X POST https://api.telegram.org/bot$telegram_token/sendMessage -d chat_id=$telegram_chatid -d text="$accountname has stopped producing blocks for $current_minutes minutes." &>/dev/null
  fi
}

#----------------------------------------------------------------------------------------------------#
# FUNCTION TO CHECK RAM AND DISK SPACE                                                               #
#----------------------------------------------------------------------------------------------------#

function check_ram_and_disk(){
  ram_used_percertage="$(free | grep Mem | awk '{print $3/$2 * 100.0}' | awk -F '.' '{print $1}')"
  max_ram="$(echo $ram_usage_threshold | tr -d '%' )"
  disk_used_percertage="$(df -h | grep -w '/' | awk '{print $5}' | tr -d '%')"
  max_disk="$(echo $disk_space_threshold | tr -d '%' )"
  if (( ram_used_percertage >= max_ram ))
  then
    curl -s -X POST https://api.telegram.org/bot$telegram_token/sendMessage -d chat_id=$telegram_chatid -d text="$servername ram usage is over the specified threshold amount." &>/dev/null
  fi
  if (( disk_used_percertage >= max_disk ))
  then
    curl -s -X POST https://api.telegram.org/bot$telegram_token/sendMessage -d chat_id=$telegram_chatid -d text="$servername disk usage is over the specified threshold amount." &>/dev/null  
  fi
}

#****************************************************************************************************#
#                                          CONFIG VARIABLES                                          #
#****************************************************************************************************#

#----------------------------------------------------------------------------------------------------#
# CREATE CONFIG FILE IF IT DOESN'T EXIST                                                             #
#----------------------------------------------------------------------------------------------------#

if [ ! -f "$config_file" ]
then
  echo "#Configuration file for the unregprod script" > "$config_file"
  echo "#Make the entries as variable=value" >> "$config_file"
  echo " " >> "$config_file"
  echo "check_info=" >> "$config_file"
  echo "check_server=" >> "$config_file"
  echo "check_producer=" >> "$config_file"
  echo "check_telegram=" >> "$config_file"
  echo "last_alert=2006-09-04" >> "$config_file"
  echo "last_status=2006-09-04" >> "$config_file"
  echo "set_server_name=" >> "$config_file"
  echo "set_account_name=" >> "$config_file"
  echo "set_telegram_token=" >> "$config_file"
  echo "set_telegram_chatid=" >> "$config_file"
  echo "ram_usage_threshold=" >> "$config_file"
  echo "disk_space_threshold=" >> "$config_file"
  echo "last_produce_minutes=" >> "$config_file"
  echo "warning_alert_threshold=" >> "$config_file"
  echo " " >> "$config_file"
fi

#----------------------------------------------------------------------------------------------------#
# GET CONFIGURATION FROM THE CONFIG FILE                                                             #
#----------------------------------------------------------------------------------------------------#

check_info="$(grep -v '^#' "$config_file" | grep '^check_info=' | awk -F '=' '{print $2}')"
check_server="$(grep -v '^#' "$config_file" | grep '^check_server=' | awk -F '=' '{print $2}')"
check_producer="$(grep -v '^#' "$config_file" | grep '^check_producer=' | awk -F '=' '{print $2}')"
alert_telegram="$(grep -v '^#' "$config_file" | grep '^alert_telegram=' | awk -F '=' '{print $2}')"
set_server_name="$(grep -v '^#' "$config_file" | grep '^set_server_name=' | awk -F '=' '{print $2}')"
set_account_name="$(grep -v '^#' "$config_file" | grep '^set_account_name=' | awk -F '=' '{print $2}')"
set_telegram_token="$(grep -v '^#' "$config_file" | grep '^ set_telegram_token=' | awk -F '=' '{print $2}')"
set_telegram_chatid="$(grep -v '^#' "$config_file" | grep '^set_telegram_chatid=' | awk -F '=' '{print $2}')"
ram_usage_threshold="$(grep -v '^#' "$config_file" | grep '^ram_usage_threshold=' | awk -F '=' '{print $2}')"
disk_space_threshold="$(grep -v '^#' "$config_file" | grep '^disk_space_threshold=' | awk -F '=' '{print $2}')"
set_producer_minutes="$(grep -v '^#' "$config_file" | grep '^last_produce_minutes=' | awk -F '=' '{print $2}')"
warning_alert_threshold="$(grep -v '^#' "$config_file" | grep '^warning_alert_threshold=' | awk -F '=' '{print $2}')"

#****************************************************************************************************#
#                                       GETTING USER VARIABLES                                       #
#****************************************************************************************************#

#----------------------------------------------------------------------------------------------------#
# CHECK FOR SERVER NAME IF SET IN THE CONFIG FILE                                                    #
#----------------------------------------------------------------------------------------------------#

if get_config_value set_server_name
then
  set_server_name="$global_value"
else
  if grep "^set_server_name" "$config_file" > /dev/null 2>&1
  then
    echo ""
    read -p "ENTER YOUR SERVER NAME?: " -e set_server_name
    sed -i "s/set_server_name=/set_server_name=$set_server_name/g" "$config_file"
  else
    set_server_name="Server 1"
    sed -i "s/set_server_name=/set_server_name=$set_server_name/g" "$config_file"
  fi
fi

#----------------------------------------------------------------------------------------------------#
# CHECK FOR PRODUCER NAME IF SET IN THE CONFIG FILE                                                  #
#----------------------------------------------------------------------------------------------------#

if get_config_value set_account_name
then
  set_account_name="$global_value"
else
  if grep "^set_account_name" "$config_file" > /dev/null 2>&1
  then
    set_account_name=$(cat config/config.ini | grep 'producer-name' | awk '{print $3}')
    sed -i "s/set_account_name=/set_account_name=$set_account_name/g" "$config_file"
  fi
fi
if grep "^set_account_name" "$config_file" > /dev/null 2>&1
then
  if [ -z "$set_account_name" ]
  then
    echo ""
    read -p "ENTER YOUR PRODUCER NAME: " -e set_account_name
    sed -i "s/set_account_name=/set_account_name=$set_account_name/g" "$config_file"
  fi
fi

#----------------------------------------------------------------------------------------------------#
# CHECK FOR REMCLI GET INFO VARIABLE IF SET IN THE CONFIG FILE                                       #
#----------------------------------------------------------------------------------------------------#

if get_config_value check_info
then
  check_info="$global_value"
else
  if grep "^check_info" "$config_file" > /dev/null 2>&1
  then
    echo ""
    if get_user_answer_yn "ENABLE CHECK FOR REMCLI GET INFO"
    then
      check_info=true
      sed -i "s/check_info=/check_info=$check_info/g" "$config_file"
    else
      check_info=false
      sed -i "s/check_info=/check_info=$check_info/g" "$config_file"
    fi
  fi
fi

#----------------------------------------------------------------------------------------------------#
# CHECK FOR SERVER CONDITION VARIABLE IF SET IN THE CONFIG FILE                                      #
#----------------------------------------------------------------------------------------------------#

if get_config_value check_server
then
  check_server="$global_value"
else
  if grep "^check_server" "$config_file" > /dev/null 2>&1
  then
    echo ""
    if get_user_answer_yn "ENABLE CHECK FOR SERVER CONDITION"
    then
      check_server=true
      sed -i "s/check_server=/check_server=$check_server/g" "$config_file"
    else
      check_server=false
      sed -i "s/check_server=/check_server=$check_server/g" "$config_file"
    fi
  fi
fi
if $check_server
then
  if get_config_value ram_usage_threshold
  then
    ram_usage_threshold="$global_value"
  else
    if grep "^ram_usage_threshold" "$config_file" > /dev/null 2>&1
    then
      echo ""
      read -p "ENTER YOUR RAM THRESHOLD PERCENTAGE: " -e ram_usage_threshold
      sed -i "s/ram_usage_threshold=/ram_usage_threshold=$ram_usage_threshold/g" "$config_file"
    fi
  fi
  if get_config_value disk_space_threshold
  then
    disk_space_threshold="$global_value"
  else
    if grep "^disk_space_threshold" "$config_file" > /dev/null 2>&1
    then
      echo ""
      read -p "ENTER YOUR DISK THRESHOLD PERCENTAGE: " -e disk_space_threshold
      sed -i "s/disk_space_threshold=/disk_space_threshold=$disk_space_threshold/g" "$config_file"
    fi
  fi
fi

#----------------------------------------------------------------------------------------------------#
# CHECK FOR PRODUCER VARIABLE IF SET IN THE CONFIG FILE                                              #
#----------------------------------------------------------------------------------------------------#

if get_config_value check_producer
then
  check_producer="$global_value"
else
  if grep "^check_producer" "$config_file" > /dev/null 2>&1
  then
    echo ""
    if get_user_answer_yn "ENABLE CHECK FOR"
    then
      check_producer=true
      sed -i "s/check_producer=/check_producer=$check_producer/g" "$config_file"
    else
      check_producer=false
      sed -i "s/check_producer=/check_producer=$check_producer/g" "$config_file"
    fi
  fi
fi
if $check_producer
then
  if get_config_value set_producer_minutes
  then
    set_producer_minutes="$global_value"
  else
    if grep "^set_producer_minutes" "$config_file" > /dev/null 2>&1
    then
      echo ""
      read -p "ENTER MINTUES TO MONITOR IF YOU'RE NOT PRODUCING?: " -e set_producer_minutes
      echo ""
      sed -i "s/set_producer_minutes=/set_producer_minutes=$set_producer_minutes/g" "$config_file"
    fi
  fi
fi

#----------------------------------------------------------------------------------------------------#
# CHECK FOR TELEGRAM VARIABLE IF SET IN THE CONFIG FILE                                              #
#----------------------------------------------------------------------------------------------------#

if get_config_value alert_telegram
then
  alert_telegram="$global_value"
else
  if grep "^alert_telegram" "$config_file" > /dev/null 2>&1
  then
    echo ""
    if get_user_answer_yn "ENABLE TELEGRAM NOTIFICATIONS"
    then
      alert_telegram=true
      sed -i "s/alert_telegram=/alert_telegram=$alert_telegram/g" "$config_file"
    else
      alert_telegram=false
      sed -i "s/alert_telegram=/alert_telegram=$alert_telegram/g" "$config_file"
    fi
  fi
fi
if $alert_telegram
then
  if get_config_value set_telegram_token
  then
    set_telegram_token="$global_value"
  else
    if grep "^set_telegram_token" "$config_file" > /dev/null 2>&1
    then
      echo ""
      read -p "ENTER YOUR TELEGRAM TOKEN API: " -e set_telegram_token
      sed -i "s/set_telegram_token=/set_telegram_token=$set_telegram_token/g" "$config_file"
    fi
  fi
  if get_config_value set_telegram_chatid
  then
    set_telegram_chatid="$global_value"
  else
    if grep "^set_telegram_chatid" "$config_file" > /dev/null 2>&1
    then
      echo ""
      read -p "ENTER YOUR TELEGRAM CHAT ID: " -e set_telegram_chatid
      sed -i "s/set_telegram_chatid=/set_telegram_chatid=$set_telegram_chatid/g" "$config_file"
    fi
  fi
fi
if $alert_telegram
then
  if get_config_value warning_alert_threshold
  then
    warning_alert_threshold="$global_value"
  else
    if grep "^warning_alert_threshold" "$config_file" > /dev/null 2>&1
    then
      echo ""
      read -p "ENTER YOUR ALERT THRESHOLD MINUTE: " -e warning_alert_threshold
      sed -i "s/warning_alert_threshold=/warning_alert_threshold=$warning_alert_threshold/g" "$config_file"
    fi
  fi
fi

#----------------------------------------------------------------------------------------------------#
# GET VARIABLES FROM THE CONFIG SOURCE                                                               #
#----------------------------------------------------------------------------------------------------#

if [ ! -z "$warning_alert_threshold" ]
then
  crontab -u root -l | grep -v 'testchain-bp-monitor'  | crontab -u root -
 (crontab -u root -l ; echo "*/$warning_alert_threshold * * * * $cron_cmd") | crontab -u root -
fi

#****************************************************************************************************#
#                                     MAIN PART OF THE SCRIPT                                        #
#****************************************************************************************************#

switch=$(cat "$state_file")
status=`ps -efww | grep -w "testchain-bp-monitor" | grep -v grep | grep -v $$ | awk '{ print $2 }'`

echo "======================================================================================="
echo "BP-Monitor script is '$switch', to disable script set file '$state_file' to 'off'"
echo "======================================================================================="
echo ""

case "$switch" in

on|On|ON) if [ -z "$status" ] 
          then
            if [ "$(echo $check_info | tr '[:upper:]' '[:lower:]' )" == "true" ]
            then
              check_remcli_info
            fi
            if [ "$(echo $check_server | tr '[:upper:]' '[:lower:]' )" == "true" ]
            then
              check_ram_and_disk
            fi
            if [ "$(echo $check_producer | tr '[:upper:]' '[:lower:]' )" == "true" ]
            then
              check_produce_minutes
            fi
          fi
        ;;

off|Off|OFF) exit
             ;;

*) exit
   ;;

esac
